controller_list:
  - name: arm_controller_position
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_joint
      - link1_joint
      - link2_joint
      - link3_joint
      - link4_joint
      - eef_joint