arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_joint
    - link1_joint
    - link2_joint
    - link3_joint
    - link4_joint
  gains:
    base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1